set encoding=utf-8

set fileformats=unix,dos,mac

syntax enable

set expandtab

set autoindent

filetype plugin indent on
set backspace=indent,eol,start



" set the runtime path to include Vundle and initialize
"set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
" let Vundle manage Vundle, required
" Plugin 'VundleVim/Vundle.vim'

"Plugin 'tpope/vim-fugitive'

"Plugin 'scrooloose/nerdtree'

"Plugin 'kien/ctrlp.vim'

"Plugin 'maxbrunsfeld/vim-emacs-bindings'

"Plugin 'elixir-lang/vim-elixir'


set autoread
set wildmenu
set nu
set ruler
set ignorecase
set smartcase
set hlsearch
set incsearch 

try
  colorscheme railscast
catch
endtry

set nobackup
set nowb
set noswapfile


" Use spaces instead of tabs
set expandtab

" Be smart when using tabs ;)
set smarttab

set shiftwidth=2
set tabstop=2

" Linebreak on 500 characters
set lbr
set tw=500

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines


""""""""""""""""""""""""""""""
" => Status line
" Always show the status line
set laststatus=2

" Format the status line
"set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c


execute pathogen#infect()
call pathogen#helptags()


"let g:solarized_termcolors=16
colorscheme railscasts

" Set 7 lines to the cursor - when moving vertically using j/k
set so=7

" ignore compiled files
set wildignore=*.o,*~,*.pyc

map <leader>ss :setlocal spell!<cr>

map <silent> <C-n> :NERDTreeFocus<CR>

