set encoding=utf-8

set fileformats=unix,dos,mac

syntax enable

set expandtab

set autoindent

filetype plugin indent on
set backspace=indent,eol,start

set autoread
set wildmenu
set nu
set ruler
set ignorecase
set smartcase
set hlsearch
set incsearch 

try
  colorscheme railscast
catch
endtry

set nobackup
set nowb
set noswapfile


" Use spaces instead of tabs
set expandtab

" Be smart when using tabs ;)
set smarttab

set shiftwidth=2
set tabstop=2

" Linebreak on 500 characters
set lbr
set tw=500

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines


""""""""""""""""""""""""""""""
" => Status line
" Always show the status line
set laststatus=2

" Format the status line
"set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c


execute pathogen#infect()
call pathogen#helptags()


"let g:solarized_termcolors=16
colorscheme summerfruit256

" Set 7 lines to the cursor - when moving vertically using j/k
set so=7

" ignore compiled files
set wildignore=*.o,*~,*.pyc

map <leader>ss :setlocal spell!<cr>

map <silent> <C-n> :NERDTreeFocus<CR>

set cursorline
autocmd InsertEnter * highlight CursorLine guibg=#000050 guifg=fg
autocmd InsertLeave * highlight CursorLine guibg=#004000 guifg=fg

nmap <C-j> :bnext<CR>
nmap <C-k> :bprevious<CR>
nmap <C-l> :ls<CR>

let g:airline#extensions#tabline#enabled = 1
imap <leader>' ''<ESC>i
imap <leader>[ []<ESC>i
imap <leader>" ""<ESC>i
imap <leader>( ()<ESC>i

nmap gO o<ESC>k

nmap n nzz
nmap N Nzz
